# Generated by Django 4.1.6 on 2023-10-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=40)),
                ('car_price', models.PositiveIntegerField()),
                ('car_picture', models.ImageField(upload_to='')),
                ('in_stock', models.BooleanField(default=True)),
                ('year_manufacture', models.DateField()),
                ('car_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carcolor', to='shop.carcolor')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmake', to='shop.carmake')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartype', to='shop.cartype')),
            ],
        ),
    ]
