# Generated by Django 4.1.6 on 2023-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem_order_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_retro',
            field=models.BooleanField(default=False),
        ),
    ]
