# Generated by Django 4.1.6 on 2023-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_car_is_retro'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desсription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
