# Generated by Django 4.1.6 on 2023-12-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_car_desсription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='desсription',
            new_name='description',
        ),
    ]
